---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: buster
    image: debian:buster
  - name: bionic
    image: ubuntu:bionic
  - name: arch
    image: archlinux/base:latest
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
